server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        if ($uri ~ ^(.+)/$) {
            set $path $1;
        }
        if (-f $document_root$path.html) {
            rewrite ^(.+)/$ $1.html last;
        }
        try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;
}
