import type { CollectionConfig } from 'payload'
import {
  isContentEditor,
  PERMISSIONS,
  userIsAdmin,
  hasPermission,
} from '../util/access'
import {
  deleteThumbnailAfterDelete,
  setPrefixFromVisibility,
  syncVisibilityStorage,
  triggerThumbnailAfterUpload,
} from '../hooks/mediaVisibility'
import { checkVideoThumb, postVideoThumb } from '../endpoints/videoThumb'
import { fileKeyFor } from '../lib/media'

export const Media: CollectionConfig = {
  slug: 'media',
  admin: {
    description: {
      en: 'Images and files uploaded for use across the website.',
      'zh-CN': '上传至网站使用的图片与文件。',
      'zh-TW': '上傳至網站使用的圖片與檔案。',
    },
  },
  access: {
    read: ({ req }) => (req.user ? true : { prefix: { not_equals: 'private' } }),
    create: isContentEditor,
    update: isContentEditor,
    delete: ({ req: { user } }) =>
      userIsAdmin(user) || hasPermission(user, PERMISSIONS.DELETE_MEDIA),
    admin: ({ req }) => Boolean(req.user),
  },
  hooks: {
    beforeChange: [setPrefixFromVisibility],
    afterChange: [syncVisibilityStorage],
    afterDelete: [deleteThumbnailAfterDelete],
    afterOperation: [triggerThumbnailAfterUpload],
  },
  endpoints: [
    {
      path: '/video-thumb/check',
      method: 'get',
      handler: checkVideoThumb,
    },
    {
      path: '/video-thumb',
      method: 'post',
      handler: postVideoThumb,
    },
  ],
  fields: [
    {
      name: 'prefix',
      type: 'text',
      defaultValue: 'public',
      admin: {
        hidden: true,
        readOnly: true,
      },
    },
    {
      name: 'alt',
      type: 'text',
      label: 'Alt Text',
      localized: true,
      required: true,
    },
    {
      name: 'category',
      type: 'relationship',
      relationTo: 'gallery-categories',
      label: 'Gallery Category',
      admin: {
        description: 'Used to group images on the gallery page.',
      },
    },
    {
      name: 'tags',
      type: 'text',
      label: 'Tags',
      hasMany: true,
      admin: {
        description: 'Optional tags for future filtering and grouping.',
      },
    },
    {
      name: 'sortOrder',
      type: 'number',
      label: 'Sort Order',
      defaultValue: 0,
      admin: {
        description: 'Position within the gallery category. Lower numbers appear first.',
      },
    },
    {
      name: 'hidden',
      type: 'checkbox',
      label: 'Hidden from Gallery',
      defaultValue: false,
      admin: {
        description: 'Hide this media from the public gallery page without deleting it.',
      },
    },
    {
      name: 'visibility',
      type: 'select',
      label: 'Visibility',
      defaultValue: 'public',
      required: true,
      options: [
        { label: 'Public', value: 'public' },
        { label: 'Private', value: 'private' },
      ],
      admin: {
        position: 'sidebar',
        description: 'Private files are only served through the CMS to logged-in users.',
      },
    },
    {
      name: 'usage',
      type: 'ui',
      admin: {
        components: {
          Field: './components/MediaUsage#default',
        },
      },
    },
    {
      name: 'videoThumbnail',
      type: 'ui',
      admin: {
        components: {
          Field: './components/VideoThumbnail#default',
        },
      },
    },
  ],
  upload: {
    // Sharp-based transforms are not supported on Cloudflare Workers yet;
    // thumbnails are generated by the sinkai-cms-thumbnails workflow instead.
    // For the admin list we use an on-the-fly Cloudflare Images resize of the
    // original so the thumbnail appears immediately even before the workflow
    // has generated the webp thumbnail.
    adminThumbnail: ({ doc }) => {
      const filename = doc.filename as string | undefined
      if (!filename) return ''
      if (doc.prefix === 'private') {
        return (doc.url as string) || ''
      }
      const base = process.env.MEDIA_PUBLIC_URL
      if (!base) return ''
      const key = fileKeyFor(doc.prefix as string | undefined, filename)
      return `${base}/cdn-cgi/image/width=320,quality=80,format=webp/${key}`
    },
    crop: false,
    focalPoint: false,
  },
}
