import type { CollectionConfig } from 'payload'
import {
  isContentEditor,
  PERMISSIONS,
  userIsAdmin,
  hasPermission,
} from '../util/access'
import {
  deleteThumbnailAfterDelete,
  setPrefixFromVisibility,
  syncVisibilityStorage,
  triggerThumbnailAfterUpload,
} from '../hooks/mediaVisibility'
import {
  revalidateWebAfterChange,
  revalidateWebAfterDelete,
} from '../hooks/triggerWebRevalidate'
import { checkVideoThumb, postVideoThumb } from '../endpoints/videoThumb'

export const Media: CollectionConfig = {
  slug: 'media',
  admin: {
    group: {
      en: 'Website',
      'zh-CN': '网站',
      'zh-TW': '網站',
    },
    description: {
      en: 'Images and files uploaded for use across the website.',
      'zh-CN': '上传至网站使用的图片与文件。',
      'zh-TW': '上傳至網站使用的圖片與檔案。',
    },
  },
  access: {
    read: ({ req }) => (req.user ? true : { prefix: { not_equals: 'private' } }),
    // Allow public uploads so the donation form can accept receipt images.
    // The form-builder plugin enforces per-field MIME type and size limits.
    create: () => true,
    update: isContentEditor,
    delete: ({ req: { user } }) =>
      userIsAdmin(user) || hasPermission(user, PERMISSIONS.DELETE_MEDIA),
    admin: ({ req }) => Boolean(req.user),
  },
  hooks: {
    beforeChange: [setPrefixFromVisibility],
    afterChange: [syncVisibilityStorage, revalidateWebAfterChange],
    afterDelete: [deleteThumbnailAfterDelete, revalidateWebAfterDelete],
    afterOperation: [triggerThumbnailAfterUpload],
  },
  endpoints: [
    {
      path: '/video-thumb/check',
      method: 'get',
      handler: checkVideoThumb,
    },
    {
      path: '/video-thumb',
      method: 'post',
      handler: postVideoThumb,
    },
  ],
  fields: [
    {
      name: 'prefix',
      type: 'text',
      defaultValue: 'public',
      admin: {
        hidden: true,
        readOnly: true,
      },
    },
    {
      name: 'alt',
      type: 'text',
      label: 'Alt Text',
      localized: true,
      required: false,
    },
    {
      name: 'category',
      type: 'relationship',
      relationTo: 'media-categories',
      label: 'Media Category',
      admin: {
        description: 'Used to organize media files. Media in this category can be shown on the gallery page.',
      },
    },
    {
      name: 'tags',
      type: 'text',
      label: 'Tags',
      hasMany: true,
      admin: {
        description: 'Optional tags for future filtering and grouping.',
      },
    },
    {
      name: 'sortOrder',
      type: 'number',
      label: 'Sort Order',
      defaultValue: 0,
      admin: {
        description: 'Position within the media category. Lower numbers appear first.',
      },
    },
    {
      name: 'hidden',
      type: 'checkbox',
      label: 'Hidden from Gallery',
      defaultValue: false,
      admin: {
        description: 'Hide this media from the public gallery page without deleting it.',
      },
    },
    {
      name: 'visibility',
      type: 'select',
      label: 'Visibility',
      defaultValue: 'public',
      required: true,
      options: [
        { label: 'Public', value: 'public' },
        { label: 'Private', value: 'private' },
      ],
      admin: {
        position: 'sidebar',
        description: 'Private files are only served through the CMS to logged-in users.',
      },
    },
    {
      name: 'usage',
      type: 'ui',
      admin: {
        components: {
          Field: './components/MediaUsage#default',
        },
      },
    },
    {
      name: 'videoThumbnail',
      type: 'ui',
      admin: {
        components: {
          Field: './components/VideoThumbnail#default',
        },
      },
    },
  ],
  upload: {
    // Sharp-based transforms are not supported on Cloudflare Workers yet;
    // thumbnails are generated by the sinkai-cms-thumbnails workflow instead.
    // For the admin list we derive the thumbnail from the stored file URL:
    // use an on-the-fly Cloudflare Images resize when the URL is absolute,
    // otherwise fall back to the original file served through the CMS.
    adminThumbnail: ({ doc }) => {
      const filename = doc.filename as string | undefined
      if (!filename) return ''
      const url = (doc.url as string) || ''
      if (!url) return ''

      if (doc.prefix === 'private') {
        return url
      }

      // Derive the thumbnail URL from the stored file URL so we do not depend on
      // process.env.MEDIA_PUBLIC_URL being available at read time (Next.js may
      // inline env vars at build time in the deployed worker). For public files
      // served from the CDN, apply an on-the-fly Cloudflare Images resize. For
      // relative URLs (local dev / legacy / no CDN configured), serve the
      // original through the CMS so the preview still appears.
      if (/^https?:\/\//i.test(url)) {
        try {
          const parsed = new URL(url)
          return `${parsed.origin}/cdn-cgi/image/width=320,quality=80,format=webp${parsed.pathname}`
        } catch {
          return url
        }
      }

      return url
    },
    crop: false,
    focalPoint: false,
  },
}
