version: "3.9"

services:
  app:
    image: ${APP_IMAGE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sinkai-dev.rule=Host(`sinkai-dev.tribalorigin.com`)"
      - "traefik.http.routers.sinkai-dev.entrypoints=websecure"
      - "traefik.http.routers.sinkai-dev.tls.certresolver=letsencrypt"
      - "traefik.http.routers.sinkai-dev.middlewares=compress@file"
      - "traefik.http.services.sinkai-dev.loadbalancer.server.port=80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - dev
    restart: unless-stopped

networks:
  dev:
    external: true
