version: "3.9"

services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    ports:
      - "5281:80"
      - "52444:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - __NETWORK__
    restart: unless-stopped
    labels:
      - "traefik.enable=false"

networks:
  __NETWORK__:
    external: true
