import type { Locale } from '../locales'

export interface MediaCategorySeed {
  slug: string
  label: Record<Locale, string>
  title: Record<Locale, string>
  description?: Record<Locale, string>
  sortOrder: number
  showInGallery: boolean
  images: string[] // full-size paths in packages/web/public
}

/**
 * Media categories and their images. Categories are rendered on the public
 * gallery page ordered by sortOrder. Text is seeded into the CMS so editors can
 * manage categories and their localized headings without code changes.
 */
export const mediaCategories: MediaCategorySeed[] = [
  {
    slug: 'snow-disaster',
    label: {
      en: 'SNOW DISASTER RELIEF',
      'zh-CN': '雪灾救援',
      'zh-TW': '雪災救援',
    },
    title: {
      en: 'Snow Disaster Relief',
      'zh-CN': '雪灾苦寒考察实况',
      'zh-TW': '雪災苦寒考察實況',
    },
    description: {
      en: 'In 2008, severe snowstorms devastated Guizhou Province. Sin Kai quickly organised relief efforts, distributing over a thousand bags of rice and two thousand quilts to 2,300+ extreme hardship households.',
      'zh-CN': '2008年极严峻的雪灾风暴笼罩整个贵州省，善启迅速组织救援，派发过千包大米及二千多张棉被给2,300多个特困户。这些照片记录了灾后的凄凉景象与我们的救援行动。',
      'zh-TW': '2008年極嚴峻的雪災風暴籠罩整個貴州省，善啓迅速組織救援，派發過千包大米及二千多張棉被給2,300多個特困戶。這些照片記錄了災後的淒涼景象與我們的救援行動。',
    },
    sortOrder: 10,
    showInGallery: true,
    images: [
      '/gallery/snow/16_01.jpg',
      '/gallery/snow/16_02.jpg',
      '/gallery/snow/16_07.jpg',
      '/gallery/snow/16_08.jpg',
      '/gallery/snow/16_09.jpg',
      '/gallery/snow/16_10.jpg',
      '/gallery/snow/16_13.jpg',
      '/gallery/snow/16_15.jpg',
      '/gallery/snow/16_23.jpg',
      '/gallery/snow/16_25.jpg',
      '/gallery/snow/16_26.jpg',
      '/gallery/snow/16_27.jpg',
      '/gallery/snow/16_28.jpg',
      '/gallery/snow/16_29.jpg',
      '/gallery/snow/16_30.jpg',
      '/gallery/snow/16_31.jpg',
      '/gallery/snow/16_32.jpg',
      '/gallery/snow/16_33.jpg',
      '/gallery/snow/16_34.jpg',
      '/gallery/snow/16_35.jpg',
      '/gallery/snow/16_36.jpg',
      '/gallery/snow/16_37.jpg',
      '/gallery/snow/16_38.jpg',
      '/gallery/snow/16_39.jpg',
      '/gallery/snow/16_40.jpg',
      '/gallery/snow/16_41.jpg',
      '/gallery/snow/16_42.jpg',
      '/gallery/snow/16_43.jpg',
      '/gallery/snow/16_44.jpg',
      '/gallery/snow/16_45.jpg',
      '/gallery/snow/16_46.jpg',
      '/gallery/snow/16_47.jpg',
      '/gallery/snow/16_48.jpg',
      '/gallery/snow/16_49.jpg',
    ],
  },
  {
    slug: 'old-schools',
    label: {
      en: 'OLD SCHOOL BUILDINGS',
      'zh-CN': '旧校舍面貌',
      'zh-TW': '舊校舍面貌',
    },
    title: {
      en: 'Old School Buildings',
      'zh-CN': '旧校舍面貌',
      'zh-TW': '舊校舍面貌',
    },
    description: {
      en: "These are the real conditions of schools in Guizhou's mountainous areas before Sin Kai's aid — mud-built dangerous structures, broken roofs, dim classrooms, yet the only place where countless children could access knowledge.",
      'zh-CN': '这些是善启援助前贵州山区的校舍真实面貌。泥沙建造的危楼、破烂的屋顶、昏暗的课室，却是无数孩子唯一获取知识的地方。',
      'zh-TW': '這些是善啓援助前貴州山區的校舍真實面貌。泥沙建造的危樓、破爛的屋頂、昏暗的課室，卻是無數孩子唯一獲取知識的地方。',
    },
    sortOrder: 20,
    showInGallery: true,
    images: [
      '/gallery/schools-old/06_osch_01.jpg',
      '/gallery/schools-old/06_osch_02.jpg',
      '/gallery/schools-old/06_osch_04.jpg',
      '/gallery/schools-old/06_osch_05.jpg',
      '/gallery/schools-old/06_osch_06.jpg',
      '/gallery/schools-old/06_osch_07.jpg',
      '/gallery/schools-old/06_osch_08.jpg',
      '/gallery/schools-old/06_osch_09.jpg',
      '/gallery/schools-old/06_osch_10.jpg',
      '/gallery/schools-old/06_osch_12.jpg',
      '/gallery/schools-old/06_osch_13.jpg',
      '/gallery/schools-old/06_osch_14.jpg',
      '/gallery/schools-old/06_osch_15.jpg',
      '/gallery/schools-old/06_osch_16.jpg',
      '/gallery/schools-old/06_osch_17.jpg',
      '/gallery/schools-old/06_osch_18.jpg',
      '/gallery/schools-old/06_osch_19.jpg',
      '/gallery/schools-old/06_osch_20.jpg',
      '/gallery/schools-old/06_osch_21.jpg',
      '/gallery/schools-old/06_osch_22.jpg',
      '/gallery/schools-old/06_osch_23.jpg',
      '/gallery/schools-old/06_osch_24.jpg',
      '/gallery/schools-old/06_osch_25.jpg',
      '/gallery/schools-old/06_osch_26.jpg',
      '/gallery/schools-old/06_osch_27.jpg',
      '/gallery/schools-old/06_osch_28.jpg',
      '/gallery/schools-old/06_osch_29.jpg',
    ],
  },
  {
    slug: 'new-schools',
    label: {
      en: 'NEW SCHOOL BUILDINGS',
      'zh-CN': '新校舍面貌',
      'zh-TW': '新校舍面貌',
    },
    title: {
      en: 'New School Buildings',
      'zh-CN': '新校舍面貌',
      'zh-TW': '新校舍面貌',
    },
    description: {
      en: "Through Sin Kai and generous donors' efforts, new Hope Primary Schools have been built in Guizhou's mountainous areas. Children finally have safe, bright learning environments.",
      'zh-CN': '经过善启及各方善长的努力，一所所崭新的希望小学在贵州山区落成。孩子们终于有了安全、明亮的学习环境。',
      'zh-TW': '經過善啓及各方善長的努力，一所所嶄新的希望小學在貴州山區落成。孩子們終於有了安全、明亮的學習環境。',
    },
    sortOrder: 30,
    showInGallery: true,
    images: [
      '/gallery/schools-new/06_osch_32.jpg',
      '/gallery/schools-new/06_osch_40.jpg',
      '/gallery/schools-new/06_osch_47.jpg',
      '/gallery/schools-new/06_osch_48.jpg',
      '/gallery/schools-new/06_osch_52.jpg',
      '/gallery/schools-new/06_osch_53.jpg',
      '/gallery/schools-new/06_osch_54.jpg',
      '/gallery/schools-new/06_osch_55.jpg',
      '/gallery/schools-new/06_osch_56.jpg',
      '/gallery/schools-new/06_osch_59.jpg',
      '/gallery/schools-new/06_osch_60.jpg',
      '/gallery/schools-new/06_osch_61.jpg',
      '/gallery/schools-new/06_osch_63.jpg',
      '/gallery/schools-new/06_osch_64.jpg',
      '/gallery/schools-new/06_osch_66.jpg',
      '/gallery/schools-new/06_osch_67.jpg',
      '/gallery/schools-new/06_osch_68.jpg',
      '/gallery/schools-new/06_osch_69.jpg',
      '/gallery/schools-new/06_osch_70.jpg',
      '/gallery/schools-new/06_osch_71.jpg',
      '/gallery/schools-new/06_osch_72.jpg',
      '/gallery/schools-new/06_osch_73.jpg',
    ],
  },
  {
    slug: 'field-trip',
    label: {
      en: 'FIELD TRIP HIGHLIGHTS',
      'zh-CN': '实地考察剪影',
      'zh-TW': '實地考察剪影',
    },
    title: {
      en: 'Field Trip Highlights',
      'zh-CN': '实地考察剪影',
      'zh-TW': '實地考察剪影',
    },
    description: {
      en: "Sin Kai volunteers visit Guizhou's impoverished mountainous areas multiple times each year, personally understanding villagers' needs, recording impoverished students' information, and monitoring school construction progress.",
      'zh-CN': '善启义工每年多次深入贵州贫困山区实地考察，亲身了解当地村民的需要，记录贫困学童的资料，监督建校工程进度。',
      'zh-TW': '善啓義工每年多次深入貴州貧困山區實地考察，親身瞭解當地村民的需要，記錄貧困學童的資料，監督建校工程進度。',
    },
    sortOrder: 40,
    showInGallery: true,
    images: [
      '/gallery/field-trip/04_02.jpg',
      '/gallery/field-trip/04_03.jpg',
      '/gallery/field-trip/04_05.jpg',
      '/gallery/field-trip/04_06.jpg',
      '/gallery/field-trip/04_07.jpg',
      '/gallery/field-trip/04_12.jpg',
      '/gallery/field-trip/04_13.jpg',
      '/gallery/field-trip/04_16.jpg',
      '/gallery/field-trip/04_17.jpg',
      '/gallery/field-trip/04_18.jpg',
      '/gallery/field-trip/04_19.jpg',
      '/gallery/field-trip/04_20.jpg',
      '/gallery/field-trip/04_25.jpg',
      '/gallery/field-trip/04_29.jpg',
      '/gallery/field-trip/04_31.jpg',
      '/gallery/field-trip/04_32.jpg',
      '/gallery/field-trip/04_33.jpg',
      '/gallery/field-trip/04_34.jpg',
      '/gallery/field-trip/04_35.jpg',
      '/gallery/field-trip/04_36.jpg',
      '/gallery/field-trip/04_37.jpg',
      '/gallery/field-trip/04_38.jpg',
      '/gallery/field-trip/04_41.jpg',
      '/gallery/field-trip/04_43.jpg',
    ],
  },
  {
    slug: 'hk-charity',
    label: {
      en: 'CHARITY IN HONG KONG',
      'zh-CN': '在港慈善活动',
      'zh-TW': '在港慈善活動',
    },
    title: {
      en: 'Charity in Hong Kong',
      'zh-CN': '在港慈善活动',
      'zh-TW': '在港慈善活動',
    },
    description: {
      en: "Each year before the Mid-Autumn Festival, Sin Kai organises the 'Mid-Autumn Love for the Elderly' event in multiple Hong Kong housing estates, distributing festival mooncakes, fruit and daily necessities to elderly residents living alone.",
      'zh-CN': '每年中秋节前夕，善启在多个香港长者屋村举办「中秋爱心敬老活动」，派发贺节月饼、水果及日用品给独居长者。',
      'zh-TW': '每年中秋節前夕，善啓在多個香港長者屋村舉辦「中秋愛心敬老活動」，派發賀節月餅、水果及日用品給獨居長者。',
    },
    sortOrder: 50,
    showInGallery: true,
    images: [
      '/gallery/hk-charity/07_02.jpg',
      '/gallery/hk-charity/07_03.jpg',
      '/gallery/hk-charity/07_04.jpg',
      '/gallery/hk-charity/07_05.jpg',
      '/gallery/hk-charity/07_08.jpg',
      '/gallery/hk-charity/07_09.jpg',
      '/gallery/hk-charity/07_10.jpg',
      '/gallery/hk-charity/07_11.jpg',
      '/gallery/hk-charity/07_12.jpg',
      '/gallery/hk-charity/07_13.jpg',
      '/gallery/hk-charity/07_15.jpg',
      '/gallery/hk-charity/07_2019ma1.jpg',
      '/gallery/hk-charity/07_2019ma2.jpg',
      '/gallery/hk-charity/07_2019ma3.jpg',
      '/gallery/hk-charity/07_2021ma1.jpg',
      '/gallery/hk-charity/07_2021ma2.jpg',
      '/gallery/hk-charity/07_20.jpg',
      '/gallery/hk-charity/07_21.jpg',
      '/gallery/hk-charity/07_24.jpg',
      '/gallery/hk-charity/07_27.jpg',
      '/gallery/hk-charity/07_28.jpg',
      '/gallery/hk-charity/07_29.jpg',
      '/gallery/hk-charity/07_30.jpg',
    ],
  },
  {
    slug: 'mountain',
    label: {
      en: 'GUIZHOU MOUNTAIN REALITY',
      'zh-CN': '贵州山区实景',
      'zh-TW': '貴州山區實景',
    },
    title: {
      en: 'Guizhou Mountain Reality',
      'zh-CN': '贵州山区实景',
      'zh-TW': '貴州山區實景',
    },
    description: {
      en: 'Guizhou Province is located on a plateau, 92.5% mountainous. These photos truthfully document the living conditions of impoverished villagers — rugged mountain roads, dilapidated houses, and rudimentary facilities.',
      'zh-CN': '贵州省地处高原，92.5%为山地。这些照片真实记录了当地贫困村民的生活环境——崎岖山路、破旧房屋、简陋的设施。',
      'zh-TW': '貴州省地處高原，92.5%爲山地。這些照片真實記錄了當地貧困村民的生活環境——崎嶇山路、破舊房屋、簡陋的設施。',
    },
    sortOrder: 60,
    showInGallery: true,
    images: [
      '/gallery/mountain/01_00.jpg',
      '/gallery/mountain/01_07.jpg',
      '/gallery/mountain/01_08.jpg',
      '/gallery/mountain/01_09.jpg',
      '/gallery/mountain/01_10.jpg',
      '/gallery/mountain/01_11.jpg',
      '/gallery/mountain/01_13.jpg',
      '/gallery/mountain/01_15.jpg',
      '/gallery/mountain/01_16.jpg',
      '/gallery/mountain/01_17.jpg',
      '/gallery/mountain/01_22.jpg',
      '/gallery/mountain/01_23.jpg',
      '/gallery/mountain/01_27.jpg',
      '/gallery/mountain/01_28.jpg',
      '/gallery/mountain/01_31.jpg',
      '/gallery/mountain/01_32.jpg',
      '/gallery/mountain/01_34.jpg',
      '/gallery/mountain/01_37.jpg',
      '/gallery/mountain/01_39.jpg',
      '/gallery/mountain/01_40.jpg',
      '/gallery/mountain/01_43.jpg',
      '/gallery/mountain/01_44.jpg',
      '/gallery/mountain/01_45.jpg',
      '/gallery/mountain/01_46.jpg',
      '/gallery/mountain/01_47.jpg',
      '/gallery/mountain/01_48.jpg',
      '/gallery/mountain/01_49.jpg',
      '/gallery/mountain/01_50.jpg',
    ],
  },
  {
    slug: 'activities',
    label: {
      en: 'ANNUAL ACTIVITIES',
      'zh-CN': '全年周期活动',
      'zh-TW': '全年週期活動',
    },
    title: {
      en: 'Annual Activities',
      'zh-CN': '全年周期活动',
      'zh-TW': '全年週期活動',
    },
    description: {
      en: 'Sin Kai regularly organises multiple annual activities, including Guizhou field trips, Mid-Autumn elderly care events, charity mooncake sales, and more, continuously bringing warmth and hope to impoverished mountainous areas.',
      'zh-CN': '善启每年定期举办多项活动，包括贵州实地考察、中秋敬老活动、慈善月饼义卖等，持续为贫困山区送去温暖与希望。',
      'zh-TW': '善啓每年定期舉辦多項活動，包括貴州實地考察、中秋敬老活動、慈善月餅義賣等，持續爲貧困山區送去溫暖與希望。',
    },
    sortOrder: 70,
    showInGallery: true,
    images: [
      '/gallery/activities/13_01.jpg',
      '/gallery/activities/13_02.jpg',
      '/gallery/activities/13_03.jpg',
      '/gallery/activities/13_04.jpg',
      '/gallery/activities/13_05.jpg',
      '/gallery/activities/13_06.jpg',
      '/gallery/activities/13_07.jpg',
      '/gallery/activities/13_11.jpg',
      '/gallery/activities/13_12.jpg',
      '/gallery/activities/13_13.jpg',
      '/gallery/activities/13_14.jpg',
      '/gallery/activities/13_15.jpg',
      '/gallery/activities/13_16.jpg',
    ],
  },
  {
    slug: 'news',
    label: {
      en: 'NEWS & MOONCAKE',
      'zh-CN': '最新资讯与月饼',
      'zh-TW': '最新資訊與月餅',
    },
    title: {
      en: 'Latest News & Mid-Autumn Mooncake',
      'zh-CN': '最新资讯与中秋月饼',
      'zh-TW': '最新資訊與中秋月餅',
    },
    description: {
      en: "Each year before the Mid-Autumn Festival, Sin Kai sells charity mooncakes with all proceeds going to school building in Guizhou's impoverished mountainous areas. Over the years, 18 Hope Schools have been built with mooncake proceeds.",
      'zh-CN': '每年中秋节前夕，善启售卖慈善月饼，所有收益悉数拨作贵州省贫困山区建校用途。多年来由月饼收益建成的希望学校已达18所。',
      'zh-TW': '每年中秋節前夕，善啓售賣慈善月餅，所有收益悉數撥作貴州省貧困山區建校用途。多年來由月餅收益建成的希望學校已達18所。',
    },
    sortOrder: 80,
    showInGallery: true,
    images: [
      '/gallery/news/15_145.jpg',
      '/gallery/news/15_146.jpg',
      '/gallery/news/15_147.jpg',
      '/gallery/news/15_148.jpg',
      '/gallery/news/15_149.jpg',
      '/gallery/news/15_News7.jpg',
      '/gallery/news/15_mooncake2018.jpg',
      '/gallery/news/15_mooncake2019.jpg',
      '/gallery/news/15_mooncake2020.jpg',
      '/gallery/news/15_mooncake2021.jpg',
    ],
  },
  {
    slug: 'others',
    label: {
      en: 'THANK YOU LETTERS & POSTERS',
      'zh-CN': '感谢信与活动海报',
      'zh-TW': '感謝信與活動海報',
    },
    title: {
      en: 'Thank You Letters & Event Posters',
      'zh-CN': '感谢信与活动海报',
      'zh-TW': '感謝信與活動海報',
    },
    description: {
      en: '',
      'zh-CN': '',
      'zh-TW': '',
    },
    sortOrder: 90,
    showInGallery: true,
    images: [
      '/gallery/others/12_01.jpg',
      '/gallery/others/12_02a.jpg',
      '/gallery/others/12_02b.jpg',
      '/gallery/others/12_03.jpg',
      '/gallery/others/12_04.jpg',
      '/gallery/others/12_05.jpg',
      '/gallery/others/12_06.jpg',
      '/gallery/others/12_07.jpg',
      '/gallery/others/12_08.jpg',
      '/gallery/others/12_09.jpg',
      '/gallery/others/12_10.jpg',
      '/gallery/others/12_11.jpg',
      '/gallery/others/12_12.jpg',
      '/gallery/others/12_13.jpg',
      '/gallery/others/12_14.jpg',
    ],
  },
]

/** @deprecated Use mediaCategories directly. */
export type GalleryCategory = string

/** @deprecated Use mediaCategories directly. */
export const gallerySections = mediaCategories
