export type GalleryCategory =
  | 'snow-disaster'
  | 'old-schools'
  | 'new-schools'
  | 'field-trip'
  | 'hk-charity'
  | 'mountain'
  | 'activities'
  | 'news'
  | 'others'

export interface GallerySection {
  category: GalleryCategory
  images: string[] // full-size paths in packages/web/public
}

/**
 * Full-size image paths for each gallery section, in the same order as
 * GalleryContent.tsx. These are uploaded to the CMS media collection and
 * tagged with the corresponding category.
 */
export const gallerySections: GallerySection[] = [
  {
    category: 'snow-disaster',
    images: [
      '/gallery/snow/16_01.jpg',
      '/gallery/snow/16_02.jpg',
      '/gallery/snow/16_07.jpg',
      '/gallery/snow/16_08.jpg',
      '/gallery/snow/16_09.jpg',
      '/gallery/snow/16_10.jpg',
      '/gallery/snow/16_13.jpg',
      '/gallery/snow/16_15.jpg',
      '/gallery/snow/16_23.jpg',
      '/gallery/snow/16_25.jpg',
      '/gallery/snow/16_26.jpg',
      '/gallery/snow/16_27.jpg',
      '/gallery/snow/16_28.jpg',
      '/gallery/snow/16_29.jpg',
      '/gallery/snow/16_30.jpg',
      '/gallery/snow/16_31.jpg',
      '/gallery/snow/16_32.jpg',
      '/gallery/snow/16_33.jpg',
      '/gallery/snow/16_34.jpg',
      '/gallery/snow/16_35.jpg',
      '/gallery/snow/16_36.jpg',
      '/gallery/snow/16_37.jpg',
      '/gallery/snow/16_38.jpg',
      '/gallery/snow/16_39.jpg',
      '/gallery/snow/16_40.jpg',
      '/gallery/snow/16_41.jpg',
      '/gallery/snow/16_42.jpg',
      '/gallery/snow/16_43.jpg',
      '/gallery/snow/16_44.jpg',
      '/gallery/snow/16_45.jpg',
      '/gallery/snow/16_46.jpg',
      '/gallery/snow/16_47.jpg',
      '/gallery/snow/16_48.jpg',
      '/gallery/snow/16_49.jpg',
    ],
  },
  {
    category: 'old-schools',
    images: [
      '/gallery/schools-old/06_osch_01.jpg',
      '/gallery/schools-old/06_osch_02.jpg',
      '/gallery/schools-old/06_osch_04.jpg',
      '/gallery/schools-old/06_osch_05.jpg',
      '/gallery/schools-old/06_osch_06.jpg',
      '/gallery/schools-old/06_osch_07.jpg',
      '/gallery/schools-old/06_osch_08.jpg',
      '/gallery/schools-old/06_osch_09.jpg',
      '/gallery/schools-old/06_osch_10.jpg',
      '/gallery/schools-old/06_osch_12.jpg',
      '/gallery/schools-old/06_osch_13.jpg',
      '/gallery/schools-old/06_osch_14.jpg',
      '/gallery/schools-old/06_osch_15.jpg',
      '/gallery/schools-old/06_osch_16.jpg',
      '/gallery/schools-old/06_osch_17.jpg',
      '/gallery/schools-old/06_osch_18.jpg',
      '/gallery/schools-old/06_osch_19.jpg',
      '/gallery/schools-old/06_osch_20.jpg',
      '/gallery/schools-old/06_osch_21.jpg',
      '/gallery/schools-old/06_osch_22.jpg',
      '/gallery/schools-old/06_osch_23.jpg',
      '/gallery/schools-old/06_osch_24.jpg',
      '/gallery/schools-old/06_osch_25.jpg',
      '/gallery/schools-old/06_osch_26.jpg',
      '/gallery/schools-old/06_osch_27.jpg',
      '/gallery/schools-old/06_osch_28.jpg',
      '/gallery/schools-old/06_osch_29.jpg',
    ],
  },
  {
    category: 'new-schools',
    images: [
      '/gallery/schools-new/06_osch_32.jpg',
      '/gallery/schools-new/06_osch_40.jpg',
      '/gallery/schools-new/06_osch_47.jpg',
      '/gallery/schools-new/06_osch_48.jpg',
      '/gallery/schools-new/06_osch_52.jpg',
      '/gallery/schools-new/06_osch_53.jpg',
      '/gallery/schools-new/06_osch_54.jpg',
      '/gallery/schools-new/06_osch_55.jpg',
      '/gallery/schools-new/06_osch_56.jpg',
      '/gallery/schools-new/06_osch_59.jpg',
      '/gallery/schools-new/06_osch_60.jpg',
      '/gallery/schools-new/06_osch_61.jpg',
      '/gallery/schools-new/06_osch_63.jpg',
      '/gallery/schools-new/06_osch_64.jpg',
      '/gallery/schools-new/06_osch_66.jpg',
      '/gallery/schools-new/06_osch_67.jpg',
      '/gallery/schools-new/06_osch_68.jpg',
      '/gallery/schools-new/06_osch_69.jpg',
      '/gallery/schools-new/06_osch_70.jpg',
      '/gallery/schools-new/06_osch_71.jpg',
      '/gallery/schools-new/06_osch_72.jpg',
      '/gallery/schools-new/06_osch_73.jpg',
    ],
  },
  {
    category: 'field-trip',
    images: [
      '/gallery/field-trip/04_02.jpg',
      '/gallery/field-trip/04_03.jpg',
      '/gallery/field-trip/04_05.jpg',
      '/gallery/field-trip/04_06.jpg',
      '/gallery/field-trip/04_07.jpg',
      '/gallery/field-trip/04_12.jpg',
      '/gallery/field-trip/04_13.jpg',
      '/gallery/field-trip/04_16.jpg',
      '/gallery/field-trip/04_17.jpg',
      '/gallery/field-trip/04_18.jpg',
      '/gallery/field-trip/04_19.jpg',
      '/gallery/field-trip/04_20.jpg',
      '/gallery/field-trip/04_25.jpg',
      '/gallery/field-trip/04_29.jpg',
      '/gallery/field-trip/04_31.jpg',
      '/gallery/field-trip/04_32.jpg',
      '/gallery/field-trip/04_33.jpg',
      '/gallery/field-trip/04_34.jpg',
      '/gallery/field-trip/04_35.jpg',
      '/gallery/field-trip/04_36.jpg',
      '/gallery/field-trip/04_37.jpg',
      '/gallery/field-trip/04_38.jpg',
      '/gallery/field-trip/04_41.jpg',
      '/gallery/field-trip/04_43.jpg',
    ],
  },
  {
    category: 'hk-charity',
    images: [
      '/gallery/hk-charity/07_02.jpg',
      '/gallery/hk-charity/07_03.jpg',
      '/gallery/hk-charity/07_04.jpg',
      '/gallery/hk-charity/07_05.jpg',
      '/gallery/hk-charity/07_08.jpg',
      '/gallery/hk-charity/07_09.jpg',
      '/gallery/hk-charity/07_10.jpg',
      '/gallery/hk-charity/07_11.jpg',
      '/gallery/hk-charity/07_12.jpg',
      '/gallery/hk-charity/07_13.jpg',
      '/gallery/hk-charity/07_15.jpg',
      '/gallery/hk-charity/07_2019ma1.jpg',
      '/gallery/hk-charity/07_2019ma2.jpg',
      '/gallery/hk-charity/07_2019ma3.jpg',
      '/gallery/hk-charity/07_2021ma1.jpg',
      '/gallery/hk-charity/07_2021ma2.jpg',
      '/gallery/hk-charity/07_20.jpg',
      '/gallery/hk-charity/07_21.jpg',
      '/gallery/hk-charity/07_24.jpg',
      '/gallery/hk-charity/07_27.jpg',
      '/gallery/hk-charity/07_28.jpg',
      '/gallery/hk-charity/07_29.jpg',
      '/gallery/hk-charity/07_30.jpg',
    ],
  },
  {
    category: 'mountain',
    images: [
      '/gallery/mountain/01_00.jpg',
      '/gallery/mountain/01_07.jpg',
      '/gallery/mountain/01_08.jpg',
      '/gallery/mountain/01_09.jpg',
      '/gallery/mountain/01_10.jpg',
      '/gallery/mountain/01_11.jpg',
      '/gallery/mountain/01_13.jpg',
      '/gallery/mountain/01_15.jpg',
      '/gallery/mountain/01_16.jpg',
      '/gallery/mountain/01_17.jpg',
      '/gallery/mountain/01_22.jpg',
      '/gallery/mountain/01_23.jpg',
      '/gallery/mountain/01_27.jpg',
      '/gallery/mountain/01_28.jpg',
      '/gallery/mountain/01_31.jpg',
      '/gallery/mountain/01_32.jpg',
      '/gallery/mountain/01_34.jpg',
      '/gallery/mountain/01_37.jpg',
      '/gallery/mountain/01_39.jpg',
      '/gallery/mountain/01_40.jpg',
      '/gallery/mountain/01_43.jpg',
      '/gallery/mountain/01_44.jpg',
      '/gallery/mountain/01_45.jpg',
      '/gallery/mountain/01_46.jpg',
      '/gallery/mountain/01_47.jpg',
      '/gallery/mountain/01_48.jpg',
      '/gallery/mountain/01_49.jpg',
      '/gallery/mountain/01_50.jpg',
    ],
  },
  {
    category: 'activities',
    images: [
      '/gallery/activities/13_01.jpg',
      '/gallery/activities/13_02.jpg',
      '/gallery/activities/13_03.jpg',
      '/gallery/activities/13_04.jpg',
      '/gallery/activities/13_05.jpg',
      '/gallery/activities/13_06.jpg',
      '/gallery/activities/13_07.jpg',
      '/gallery/activities/13_11.jpg',
      '/gallery/activities/13_12.jpg',
      '/gallery/activities/13_13.jpg',
      '/gallery/activities/13_14.jpg',
      '/gallery/activities/13_15.jpg',
      '/gallery/activities/13_16.jpg',
    ],
  },
  {
    category: 'news',
    images: [
      '/gallery/news/15_145.jpg',
      '/gallery/news/15_146.jpg',
      '/gallery/news/15_147.jpg',
      '/gallery/news/15_148.jpg',
      '/gallery/news/15_149.jpg',
      '/gallery/news/15_News7.jpg',
      '/gallery/news/15_mooncake2018.jpg',
      '/gallery/news/15_mooncake2019.jpg',
      '/gallery/news/15_mooncake2020.jpg',
      '/gallery/news/15_mooncake2021.jpg',
    ],
  },
  {
    category: 'others',
    images: [
      '/gallery/others/12_01.jpg',
      '/gallery/others/12_02a.jpg',
      '/gallery/others/12_02b.jpg',
      '/gallery/others/12_03.jpg',
      '/gallery/others/12_04.jpg',
      '/gallery/others/12_05.jpg',
      '/gallery/others/12_06.jpg',
      '/gallery/others/12_07.jpg',
      '/gallery/others/12_08.jpg',
      '/gallery/others/12_09.jpg',
      '/gallery/others/12_10.jpg',
      '/gallery/others/12_11.jpg',
      '/gallery/others/12_12.jpg',
      '/gallery/others/12_13.jpg',
      '/gallery/others/12_14.jpg',
    ],
  },
]
