/**
 * One-off cleanup: remove media documents whose filename indicates they are
 * legacy thumbnails (e.g. `01_00-thumb.jpg` or Payload-deduplicated
 * `01_00-thumb-4.jpg`). These should not be managed as standalone CMS media
 * because thumbnails are now generated by the sinkai-cms-thumbnails workflow.
 *
 * For unreferenced thumb media, the script deletes the document. Payload's
 * afterDelete hook (`deleteThumbnailAfterDelete`) removes the generated R2
 * thumbnail, and the storage adapter removes the original R2 object.
 *
 * For referenced thumb media, the script attempts to repair the references by
 * uploading the corresponding full-size image (looked up under
 * `packages/web/public/gallery/`) and rewriting the relationships/inline
 * content to point to the replacement document.
 *
 * Run locally (local bindings):
 *   npm run remove:thumb-media
 *
 * Run against REMOTE staging bindings:
 *   npm run remove:thumb-media:remote
 *
 * Run against REMOTE production bindings:
 *   npm run remove:thumb-media:production
 *
 * Dry-run to preview what would be deleted/repaired:
 *   DRY_RUN=true npm run remove:thumb-media
 */

import { config as dotenvConfig } from 'dotenv'
import fs from 'fs'
import path from 'path'
import { getPayload } from 'payload'
import type { Payload } from 'payload'
import { getCfEnv } from '../lib/cloudflareEnv'
import { thumbKeyFor } from '../lib/media'

dotenvConfig({ path: '.env' })

const DRY_RUN = process.env.DRY_RUN === 'true'
const PAGE_SIZE = 50

const webPublicDir = path.resolve(process.cwd(), '../web/public')

interface Reference {
  collection: string
  id: number | string
  label: string
}

function findUploadIds(node: unknown, ids: Set<number | string>) {
  if (!node || typeof node !== 'object') return
  const n = node as Record<string, unknown>

  if (n.type === 'upload' && n.value && typeof n.value === 'object') {
    const value = n.value as Record<string, unknown>
    if (value.id !== undefined) {
      ids.add(value.id as number | string)
    }
  }

  if (Array.isArray(n.children)) {
    for (const child of n.children) {
      findUploadIds(child, ids)
    }
  }
}

function replaceUploadIds(node: unknown, oldId: number | string, newId: number | string): unknown {
  if (!node || typeof node !== 'object') return node
  const n = node as Record<string, unknown>

  if (n.type === 'upload' && n.value && typeof n.value === 'object') {
    const value = n.value as Record<string, unknown>
    if (value.id === oldId) {
      return {
        ...n,
        value: { ...value, id: newId },
      }
    }
    return n
  }

  if (Array.isArray(n.children)) {
    return {
      ...n,
      children: n.children.map((child) => replaceUploadIds(child, oldId, newId)),
    }
  }

  return n
}

async function collectReferences(
  payload: Payload,
  mediaId?: number | string,
): Promise<Reference[]> {
  if (!mediaId) return []

  const references: Reference[] = []

  const blogs = await payload.find({
    collection: 'blogs',
    depth: 0,
    limit: 1000,
    where: { coverImage: { equals: mediaId } },
  })
  for (const doc of blogs.docs) {
    references.push({
      collection: 'blogs',
      id: doc.id,
      label: (doc.title as string) || `Blog ${doc.id}`,
    })
  }

  const installations = await payload.find({
    collection: 'installations',
    depth: 0,
    limit: 1000,
    where: { photos: { contains: mediaId } },
  })
  for (const doc of installations.docs) {
    references.push({
      collection: 'installations',
      id: doc.id,
      label: (doc.title as string) || `Installation ${doc.id}`,
    })
  }

  const testimonies = await payload.find({
    collection: 'testimonies',
    depth: 0,
    limit: 1000,
    where: { photos: { contains: mediaId } },
  })
  for (const doc of testimonies.docs) {
    references.push({
      collection: 'testimonies',
      id: doc.id,
      label: (doc.name as string) || `Testimony ${doc.id}`,
    })
  }

  const pages = await payload.find({
    collection: 'pages',
    depth: 0,
    limit: 1000,
    where: { coverImage: { equals: mediaId } },
  })
  for (const doc of pages.docs) {
    references.push({
      collection: 'pages',
      id: doc.id,
      label: (doc.title as string) || `Page ${doc.id}`,
    })
  }

  const allBlogs = await payload.find({ collection: 'blogs', depth: 0, limit: 1000 })
  for (const doc of allBlogs.docs) {
    const ids = new Set<number | string>()
    findUploadIds(doc.content, ids)
    if (ids.has(mediaId)) {
      references.push({
        collection: 'blogs',
        id: doc.id,
        label: `${(doc.title as string) || `Blog ${doc.id}`} (inline content)`,
      })
    }
  }

  const allPages = await payload.find({ collection: 'pages', depth: 0, limit: 1000 })
  for (const doc of allPages.docs) {
    const ids = new Set<number | string>()
    findUploadIds(doc.content, ids)
    if (ids.has(mediaId)) {
      references.push({
        collection: 'pages',
        id: doc.id,
        label: `${(doc.title as string) || `Page ${doc.id}`} (inline content)`,
      })
    }
  }

  return references
}

function isThumbFilename(filename: string): boolean {
  // Matches legacy thumbnail filenames including Payload's auto-dedupe suffix.
  // Examples: `01_00-thumb.jpg`, `13_06-thumb-9.jpg`, `cover-thumb-1.png`
  return /-thumb(?:-\d+)?\./i.test(filename)
}

function fullSizeFilename(filename: string): string | undefined {
  const match = filename.match(/^(.+?)-thumb(?:-\d+)?(\.[^.]+)$/i)
  if (!match) return undefined
  return `${match[1]}${match[2]}`
}

function resolveFullSizePath(filename: string): string | undefined {
  const base = fullSizeFilename(filename)
  if (!base) return undefined

  const candidates: string[] = []
  function walk(dir: string) {
    const entries = fs.readdirSync(dir, { withFileTypes: true })
    for (const entry of entries) {
      const full = path.join(dir, entry.name)
      if (entry.isDirectory()) {
        walk(full)
      } else if (entry.isFile() && entry.name.toLowerCase() === base.toLowerCase()) {
        candidates.push(full)
      }
    }
  }

  const galleryDir = path.join(webPublicDir, 'gallery')
  if (fs.existsSync(galleryDir)) {
    walk(galleryDir)
  }

  return candidates[0]
}

async function repairReferences(
  payload: Payload,
  oldId: number | string,
  newId: number | string,
  refs: Reference[],
): Promise<void> {
  const grouped = new Map<string, Reference[]>()
  for (const ref of refs) {
    const list = grouped.get(ref.collection) || []
    list.push(ref)
    grouped.set(ref.collection, list)
  }

  for (const [collection, collectionRefs] of grouped) {
    for (const ref of collectionRefs) {
      const doc = (await payload.findByID({
        collection: collection as 'blogs' | 'installations' | 'testimonies' | 'pages',
        id: ref.id,
        depth: 0,
      })) as unknown as Record<string, unknown>

      const data: Record<string, unknown> = {}

      if (collection === 'blogs' || collection === 'pages') {
        if (doc.coverImage === oldId) {
          data.coverImage = newId
        }
        if (doc.content) {
          const updated = replaceUploadIds(doc.content, oldId, newId)
          if (updated !== doc.content) {
            data.content = updated
          }
        }
      } else if (collection === 'installations' || collection === 'testimonies') {
        const photos = doc.photos as Array<number | string> | undefined
        if (Array.isArray(photos) && photos.includes(oldId)) {
          data.photos = photos.map((id) => (id === oldId ? newId : id))
        }
      }

      if (Object.keys(data).length > 0) {
        await payload.update({
          collection: collection as 'blogs' | 'installations' | 'testimonies' | 'pages',
          id: ref.id,
          data,
          depth: 0,
          overrideAccess: true,
        })
      }
    }
  }
}

function normalizeVisibility(value: unknown): 'public' | 'private' {
  if (value === 'public' || value === 'private') return value
  return 'public'
}

async function deleteR2Thumbnail(filename: string): Promise<void> {
  try {
    const env = await getCfEnv()
    if (!env.R2) return
    await env.R2.delete(thumbKeyFor(filename))
  } catch {
    // Best-effort cleanup; the afterDelete hook also attempts this.
  }
}

async function createReplacementMedia(
  payload: Payload,
  oldDoc: Record<string, unknown>,
  filePath: string,
): Promise<Record<string, unknown>> {
  const data: Record<string, unknown> = {
    alt: oldDoc.alt,
    category: oldDoc.category,
    sortOrder: oldDoc.sortOrder,
    hidden: oldDoc.hidden,
    visibility: normalizeVisibility(oldDoc.visibility),
  }

  return (await payload.create({
    collection: 'media',
    data: data as any,
    filePath,
    depth: 0,
    overrideAccess: true,
  })) as unknown as Record<string, unknown>
}

async function main() {
  const { default: config } = await import('@payload-config')
  const payload = await getPayload({ config })

  let page = 1
  let scanned = 0
  let deleted = 0
  let repaired = 0
  let skipped = 0
  let failed = 0
  const notRepairable: Array<{ id: number | string; filename: string; refs: Reference[]; reason: string }> = []

  console.log(`[remove-thumb-media] DRY_RUN=${DRY_RUN}`)

  for (;;) {
    const result = await payload.find({
      collection: 'media',
      depth: 0,
      limit: PAGE_SIZE,
      page,
      overrideAccess: true,
    })

    if (result.docs.length === 0) break

    for (const doc of result.docs) {
      const filename = doc.filename as string | undefined
      scanned++

      if (!filename || !isThumbFilename(filename)) {
        skipped++
        continue
      }

      const refs = await collectReferences(payload, doc.id)

      if (refs.length === 0) {
        if (DRY_RUN) {
          console.log(`[remove-thumb-media] would delete ${filename} (id=${doc.id})`)
          deleted++
          continue
        }

        try {
          await payload.delete({
            collection: 'media',
            id: doc.id,
            overrideAccess: true,
          })
          await deleteR2Thumbnail(filename)
          deleted++
          console.log(`[remove-thumb-media] deleted ${filename} (id=${doc.id})`)
        } catch (err) {
          failed++
          console.error(`[remove-thumb-media] failed to delete ${filename} (id=${doc.id}):`, err)
        }
        continue
      }

      // Referenced: try to repair by uploading the full-size image.
      const fullSizePath = resolveFullSizePath(filename)
      if (!fullSizePath) {
        notRepairable.push({
          id: doc.id,
          filename,
          refs,
          reason: `full-size image not found in ${webPublicDir}/gallery`,
        })
        skipped++
        console.warn(
          `[remove-thumb-media] ${filename} (id=${doc.id}) is referenced but full-size file not found; skipping.`,
        )
        continue
      }

      if (DRY_RUN) {
        console.log(
          `[remove-thumb-media] would repair ${refs.length} reference(s) for ${filename} (id=${doc.id}) with ${fullSizePath}, then delete it`,
        )
        repaired++
        deleted++
        continue
      }

      try {
        const newDoc = await createReplacementMedia(payload, doc as unknown as Record<string, unknown>, fullSizePath)
        await repairReferences(payload, doc.id, newDoc.id as number | string, refs)
        await payload.delete({
          collection: 'media',
          id: doc.id,
          overrideAccess: true,
        })
        await deleteR2Thumbnail(filename)
        repaired++
        deleted++
        console.log(
          `[remove-thumb-media] repaired and deleted ${filename} (id=${doc.id}) -> replacement id=${newDoc.id}`,
        )
      } catch (err) {
        failed++
        console.error(`[remove-thumb-media] failed to repair ${filename} (id=${doc.id}):`, err)
      }
    }

    if (!result.hasNextPage) break
    page++
  }

  console.log(
    `[remove-thumb-media] done. scanned=${scanned} deleted=${deleted} repaired=${repaired} skipped=${skipped} failed=${failed}`,
  )

  if (notRepairable.length > 0) {
    console.log('\n[remove-thumb-media] referenced thumb media that could not be repaired:')
    for (const item of notRepairable) {
      console.log(`  - ${item.filename} (id=${item.id}): ${item.reason}`)
      for (const ref of item.refs) {
        console.log(`      ${ref.collection} ${ref.id}: ${ref.label}`)
      }
    }
  }

  await cleanupOrphanR2Thumbnails(payload)

  process.exit(failed > 0 ? 1 : 0)
}

async function cleanupOrphanR2Thumbnails(payload: Payload): Promise<void> {
  const env = await getCfEnv().catch((): undefined => undefined)
  if (!env?.R2) {
    console.log('[remove-thumb-media] R2 binding not available; skipping orphan thumbnail cleanup.')
    return
  }

  const mediaBasenames = new Set<string>()
  let mediaPage = 1
  for (;;) {
    const result = await payload.find({
      collection: 'media',
      depth: 0,
      limit: PAGE_SIZE,
      page: mediaPage,
      overrideAccess: true,
    })
    for (const doc of result.docs) {
      const filename = doc.filename as string | undefined
      if (filename) {
        mediaBasenames.add(filename.replace(/\.[^.]+$/, ''))
      }
    }
    if (!result.hasNextPage) break
    mediaPage++
  }

  const prefix = 'public/thumbnails/'
  const thumbPattern = /-thumb/i
  let cursor: string | undefined
  let checked = 0
  let removed = 0
  let r2Failed = 0

  for (;;) {
    const list = await env.R2.list({ prefix, cursor })
    for (const obj of list.objects) {
      checked++
      if (!thumbPattern.test(obj.key)) continue
      if (!obj.key.endsWith('.webp')) continue

      const basename = obj.key.slice(prefix.length, -'.webp'.length)
      if (mediaBasenames.has(basename)) continue

      if (DRY_RUN) {
        console.log(`[remove-thumb-media] would delete orphan R2 thumbnail ${obj.key}`)
        removed++
        continue
      }

      try {
        await env.R2.delete(obj.key)
        removed++
        console.log(`[remove-thumb-media] deleted orphan R2 thumbnail ${obj.key}`)
      } catch (err) {
        r2Failed++
        console.error(`[remove-thumb-media] failed to delete orphan R2 thumbnail ${obj.key}:`, err)
      }
    }
    if (list.truncated) {
      cursor = list.cursor
    } else {
      break
    }
  }

  console.log(
    `[remove-thumb-media] R2 orphan cleanup done. checked=${checked} removed=${removed} failed=${r2Failed}`,
  )
}

main().catch((err) => {
  console.error('[remove-thumb-media] fatal:', err)
  process.exit(1)
})
